DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS logs CASCADE;

CREATE TABLE recipes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  directions TEXT[],
  ingredients JSONB[]
);

CREATE TABLE logs (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  date_of_event DATE NOT NULL,
  notes TEXT,
  rating INT
);